Create database movies;
Use movies;
CREATE TABLE movies_info(id int,m_name varchar(30),m_language varchar(20),no_of_actors int,m_budget bigint,m_collection bigint,m_success boolean);
ALTER TABLE movies_info ADD COLUMN m_director varchar(20);
ALTER TABLE movies_info add column (m_release_date varchar(50),m_hero varchar(20));
ALTER TABLE movies_info RENAME COLUMN m_name TO movie_name;
ALTER TABLE movies_info RENAME COLUMN m_language to movie_language;
ALTER TABLE movies_info RENAME COLUMN no_of_actors to no_actors_in_movie;
ALTER TABLE movies_info RENAME COLUMN m_budget to movie_budget_cr;
ALTER TABLE movies_info RENAME COLUMN m_collection to movie_collection_cr;
INSERT INTO movies_info values(1,'Adhu jeevitham','Tamil',234,123,1098,True,'Atlee','23/05/2024','Sathish');
INSERT INTO movies_info values(2,'Maharaja','Kannada',342,789,2089,true,'S Shankar','23/03/2024','Ram');
INSERT INTO movies_info values(3,'the watches','English',456,890,3452,true,'Prashanth Neel','23/01/2024','Ranbir');
INSERT INTO movies_info values(4,'hot spot','Tamil',109,678,675,true,'Lokesh','17/04/2024','Suresh');
INSERT INTO movies_info values(5,'yuva','Kannada',897,456,8123,true,'Atlee','10/05/2024','Yuva');
INSERT INTO movies_info values(6,'rasavathi','Kannada',345,543,234,true,'Dhananjay','7/04/2024','Dhananjay');
INSERT INTO movies_info values(7,'PT sir','Telugu',234,789,645,false,'Mani ratnam','9/05/2024','Vicky');
INSERT INTO movies_info values(8,'Aramane4','Telugu',123,167,9078,false,'Rajmouli','15/05/2024','Sharavana');
INSERT INTO movies_info values(9,'Bade miyan chote','Hindi',514,789,4567,true,'Yograjbhatt','23/06/2024','Amir');
INSERT INTO movies_info values(10,'kotee','Kannada',856,834,234,true,'Prashanth Neel','2/07/2024','Dhananjay');
UPDATE movies_info SET movie_budget_cr=456 where id=4;
SELECT *FROM movies_info
UPDATE movies_info SET movie_budget_cr=456 where id=4;
UPDATE movies_info SET movie_collection_cr=752 where id=9;
UPDATE movies_info SET m_success=false where id=1;
UPDATE movies_info SET movie_budget_cr=1092 where id=6;
UPDATE movies_info SET movie_language='kannada' where id=3;
UPDATE movies_info SET movie_collection_cr=3987 where id=5;
UPDATE movies_info SET no_actors_in_movie=456 where id=8;
UPDATE movies_info SET m_release_date='17/09/2024' where id=4;
UPDATE movies_info SET m_hero='yash' where id=10;
DELETE FROM movies_info where id=5;
rollback;
DELETE FROM movies_info where movie_name='hot spot';
DELETE FROM movies_info where m_hero='Ram';
rollback;
DELETE FROM movies_info where id=1;
UPDATE movies_info SET m_hero='Rajmouli' where id=5 or movie_language='Kannda';
SELECT * FROM movies_info where id in (5,6,9,7,10);
SELECT * FROM movies_info where id not in (7,10);
SELECT * FROM movies_info where id=8 AND id=1;

Create database bank;
Use bank;
CREATE TABLE bank_details(id int,b_name varchar(50), b_branch varchar(20),b_pincode bigint,b_phno bigint);
ALTER TABLE bank_details ADD COLUMN b_id int;
ALTER TABLE bank_details add column (account_type varchar(20),b_manager varchar(30),b_country varchar(20));
ALTER TABLE bank_details ADD COLUMN bank_security boolean;
ALTER TABLE bank_details RENAME COLUMN b_name TO bank_name;
ALTER TABLE bank_details RENAME COLUMN b_branch to bank_branch;
ALTER TABLE bank_details RENAME COLUMN b_pincode to bank_pincode;
ALTER TABLE bank_details RENAME COLUMN b_id to bank_id;
ALTER TABLE bank_details RENAME COLUMN b_manager to bank_manager;
INSERT INTO bank_details values(1,'state bank','nelamangala',562123,08097976565,1098,'savings','Sathish','India',true);
INSERT INTO bank_details values(2,'icic bank','bangalore',560089,080989896565,2089,'joint','Ram','India',true);
INSERT INTO bank_details values(3,'bank of baroda','mangalore',542123,08097970000,3452,'zero','Ranbir','India',true);
INSERT INTO bank_details values(4,'state bank','nelamanagala',562123,08097565665,675,'business','Suresh','India',true);
INSERT INTO bank_details values(5,'punjab bank','bangalore',560003,08097900005,8123,'savings','Yuva','India',true);
INSERT INTO bank_details values(6,'federal bank','bangalore',560098,08096868565,234,'savings','Dhananjay','India',true);
INSERT INTO bank_details values(7,'janatha seva bank','hubli',552023,08090000565,645,'student','Vicky','India',true);
INSERT INTO bank_details values(8,'icic bank','dharwad',532123,08097343465,9078,'joint','Rajmouli','India',true);
INSERT INTO bank_details values(9,'icic bank','mangalore',500123,08097989895,4567,'joint','Yograjbhatt','India',true);
INSERT INTO bank_details values(10,'state bank','nelamangala',562123,08098989565,234,'zero','Dhananjay','India',true);
UPDATE bank_details SET bank_name='karnataka bank' where id=4;
SELECT *FROM bank_details;
UPDATE bank_details SET bank_security=false where bank_name='mangalore';
UPDATE bank_details SET b_phno=998989007 where id=9;
UPDATE bank_details SET bank_security=false where id=1;
UPDATE bank_details SET bank_id=1092 where id=6;
UPDATE bank_details SET account_type='savings' where id=3;
UPDATE bank_details SET bank_branch='punjab' where id=5;
UPDATE bank_details SET bank_pincode=560980 where id=8;
UPDATE bank_details SET bank_manager='ranbir' where id=4;
UPDATE bank_details SET b_country='korea' where id=10;
DELETE FROM bank_details where id=5;
rollback;
DELETE FROM bank_details where bank_name='punjab bank';
DELETE FROM bank_details where bank_manager='sathish';
rollback;
DELETE FROM bank_details where id=1;
UPDATE bank_details SET b_country='US' where id=5 or bank_name='state bank';
SELECT * FROM bank_details where id in (5,6,9,7,10);
SELECT * FROM bank_details where id not in (7,10);
SELECT * FROM bank_details where id=8 AND id=1;

